{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "obv-gestion.secretName" . }}
  labels:
    {{- include "obv-gestion.backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USER: {{ .Values.secrets.dbUser | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  MAIL_USER: {{ .Values.secrets.mailUser | quote }}
  MAIL_PASSWORD: {{ .Values.secrets.mailPassword | quote }}
  TWILIO_ACCOUNT_SID: {{ .Values.secrets.twilioAccountSid | quote }}
  TWILIO_AUTH_TOKEN: {{ .Values.secrets.twilioAuthToken | quote }}
  TWILIO_FROM_NUMBER: {{ .Values.secrets.twilioFromNumber | quote }}
  ORANGE_CLIENT_ID: {{ .Values.secrets.orangeClientId | quote }}
  ORANGE_CLIENT_SECRET: {{ .Values.secrets.orangeClientSecret | quote }}
  ORANGE_SENDER_ADDRESS: {{ .Values.secrets.orangeSenderAddress | quote }}
  BOOTSTRAP_ADMIN_NOM: {{ .Values.secrets.bootstrapAdminNom | quote }}
  BOOTSTRAP_ADMIN_PRENOMS: {{ .Values.secrets.bootstrapAdminPrenoms | quote }}
  BOOTSTRAP_ADMIN_CANAL: {{ .Values.secrets.bootstrapAdminCanal | quote }}
  BOOTSTRAP_ADMIN_EMAIL: {{ .Values.secrets.bootstrapAdminEmail | quote }}
  BOOTSTRAP_ADMIN_TELEPHONE: {{ .Values.secrets.bootstrapAdminTelephone | quote }}
{{- end }}
